# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Planting dates"
  url = "#demo"
  weight = 10
  
[[main]]
  name = "Spacing"
  url = "#spacing"
  weight = 20
  
[[main]]
  name = "Harvest"
  url = "#harvest"
  weight = 30

[[main]]
  name = "About"
  url = "#contact"
  weight = 40

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
